#!/bin/bash
# This runs whatever command is necessary to get ROSE installed.

set -e
dir0="${0%/*}"
arg0="rmc ${0##*/}"

source "$SPOCK_SCRIPTS/impl/basic-support.sh" || exit 1

show_help_and_exit() {
    #     --------------------------------------------------------------------------------
    echo "Usage:   $arg0 [SWITCHES]"
    echo
    echo "Purpose: Runs an installation command that installs the ROSE library. This does"
    echo "         not include configuring the build tree, but it does run all the"
    echo "         subsequent tests to build the ROSE library, test the library, and"
    echo "         install the library."
    echo
    echo "Switches:"
    echo "         --no-tests"
    echo "             Don't run any tests first. This can be used to install a version"
    echo "             of ROSE that doesn't pass and should only be used for development,"
    echo "             not actual releases intended for users."
    echo
    echo "         --prefix=DIRECTORY"
    echo "             Directory into which ROSE should be installed. For cmake and GNU"
    echo "             Autotools builds, if a directory is specified here it must match"
    echo "             the intallation prefix directory that was specified during the"
    echo "             configuration step; tup is able to retarget the installation to"
    echo "             any directory during the install step."
    exit 0
}

run_tests=yes
dry_run=
prefix=
while [ "$#" -gt 0 ]; do
    case "$1" in
	--) shift; break ;;
	-h|--help) show_help_and_exit; shift ;;
	-n|--dry-run) dry_run=--dry-run; shift ;;
	--tests) run_tests=yes; shift ;;
	--no-tests) run_tests=; shift ;;
	--prefix=*) prefix="${1#--prefix=}"; shift ;;
	-*) die "unknown command-line switch \"$1\"" ;;
	*) die "incorrect usage; see --help" ;;
    esac
done

case "$RMC_BUILD" in
    autoconf)
	if [ -n "$prefix" ]; then
	    old_prefix="$(sed -n 's/^prefix[ \t]*=[ \t]*//p' "$RG_BLD/Makefile")"
	    if [ "$old_prefix" != "$prefix" ]; then
		echo "$arg0: error: you cannot change the installation prefix for GNU Autotools builds" >&2
		echo "$arg0: info: originally specified prefix was \"$old_prefix\"" >&2
		echo "$arg0: info: newly specified prefix is \"$prefix\"" >&2
		exit 1
	    fi
	fi
	
	"$dir0/make" -C "$RG_BLD/src" $dry_run
	[ -n "$run_tests" ] && "$dir0/make" -C "$RG_BLD" $dry_run check
	"$dir0/make" -C "$RG_BLD" $dry_run install-rose-library
	"$dir0/make" -C "$RG_BLD/tools/BinaryAnalysis" $dry_run install
	;;

    cmake)
	if [ -n "$prefix" ]; then
	    old_prefix="$(sed -n 's/^CMAKE_INSTALL_PREFIX:.*=//p' "$RG_BLD/CMakeCache.txt")"
	    if [ "$old_prefix" != "$prefix" ]; then
		echo "$arg0: error: you canot change the installation prefix for CMake builds" >&2
		echo "$arg0: info: originally specified prefix was \"$old_prefix\"" >&2
		echo "$arg0: info: newly specified prefix is \"$prefix\"" >&2
		exit 1
	    fi
	fi
	
	"$dir0/make" -C "$RG_BLD/src" $dry_run
	[ -n "$run_tests" ] && die "I don't know how to run ROSE tests with CMake"
	"$dir0/make" -C "$RG_BLD" install
	;;

    tup)
	# Tup install automatically runs tests
	if [ -n "$run_tests" ]; then
	    env RMC_INSTALLED=$prefix "$dir0/make" -C "$RG_BLD" install
	else
	    "$dir0/make" -C "$RG_BLD/src"
	    (
		set -x
		cd "$RG_BLD"
		$RG_SRC/scripts/tup/install-staged --next --build-type=untested \
						   --exclude='projects/MatrixTestingProject/*' \
						   $prefix
	    )
	fi
	;;
    *)
	die "unknown build system: $RMC_BUILD"
	;;
esac
